service: wiseprod

image: tremic/wiseprod

servers:
  web:
    hosts:
      - 147.79.114.207
    proxy: false
    options:
      publish:
        - "127.0.0.1:3020:80"

registry:
  username: tremic
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - OPENAI_API_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "wiseprod_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
